name: Build and Push Docker image to GHCR

env:
  IMAGE_NAME: reductdims

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_push_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build
        run: docker build -t ${{ github.repository_owner }}/${{ env.IMAGE_NAME }} .

      - name: Test
        run: docker run --rm -v $(pwd):/work ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest Rscript work/test.R

      - name: Tag (Latest)
        run: docker tag ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest

      - name: Tag (SHA)
        run: docker tag ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }} ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}

      - name: Login
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u USERNAME --password-stdin

      - name: Push (Latest)
        run: docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest

      - name: Push (SHA)
        run: docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}

# https://github.com/marketplace/actions/docker-login
# https://github.com/inutano/cwl-log-generator/blob/master/.github/workflows/main.yml