name: Build and Push Docker image to GHCR

env:
  IMAGE_NAME: reductdims

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_push_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build
        run: docker build -t ${{ github.repository_owner }}/${{ env.IMAGE_NAME }} .

      - name: Test
        run: docker run --rm -v $(pwd):/work ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest Rscript work/test.R

      - name: Tag
        run: docker tag ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}

      - name: Push (Latest)
        run: docker push ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest

      - name: Push (SHA)
        run: docker push ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}

# https://github.com/marketplace/actions/docker-login
# https://github.com/inutano/cwl-log-generator/blob/master/.github/workflows/main.yml