name: Test R-script

env:
  IMAGE_NAME: reductdims

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          check-name: 'Build and push'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Test
        run: docker run -it --rm ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest Rscript test.R

# https://github.com/marketplace/actions/wait-on-check